### ISSUE TITLE
One cannot simply change the (possibly invariant) lifetime in `<R as RefType<'s>>::Ref`

### ISSUE THREAD

**Issue by steffahn** [prokopyl/selfie#2]
So in particular, your function signatures for `referential`, `with_referential`, and `with_referential_mut` are ***all unsound***.

The latter two can be fixed, look at the kinds of signatures that ouroboros or self_cell generate to see what approach can work soundly. On the other hand, the function `referential` is entirely impossible to write soundly, as far as I’m aware, without resorting to macros or unsafe traits, in order to check for *covariance* so that the lifetime of `<R as RefType<'s>>::Ref` is legal to change.

---

“But where did any lifetimes change?” – the change happens by the fact that the callbacks or return value in this API receives a reference to `<R as RefType<'s>>::Ref` where `'s` is taken from the lifetime of `&'s self`. Since every borrow of `self` in subsequent calls is a new borrow with a different lifetime, you just give inconsistently typed views of `<R as RefType<'s>>::Ref` with different short-lived lifetimes, which will be unsound if `'s` is *not* covariant in `<R as RefType<'s>>::Ref` (`with_referential_mut` is unsound regardless of variance).

For example, if you use `<R as RefType<'s>>::Ref` = `Cell<&'a …>`, then one call to `with_referential`/`with_referential_mut` allows placing something way-too-shortlived into that cell, and the next call can access it after free:
```rs
use selfie::{refs::RefType, Selfie};
use std::cell::Cell;

struct CellRefStr;
impl<'a> RefType<'a> for CellRefStr {
    type Ref = Cell<&'a str>;
}

fn main() {
    let x = Selfie::<_, CellRefStr>::new(Box::pin(()), |_| Cell::new(""));
    let s = String::from("Hello World");
    x.with_referential(|r| r.set(&s));
    let r: &str = x.with_referential(|r| r.get());
    println!("String exists: {r}");
    drop(s);
    println!("String used after free: {r}");
}
```
Of course, the above works just as well with `with_referential_mut`.

For `referential`, we need a `Copy` type; but for instance `&'a Cell<&'a …>` will work fine (with a little bit of leaking in order to construct it).
```rs
use selfie::{refs::RefType, Selfie};
use std::cell::Cell;

struct RefCellRefStr;
impl<'a> RefType<'a> for RefCellRefStr {
    type Ref = &'a Cell<&'a str>;
}

fn main() {
    let x = Selfie::<_, RefCellRefStr>::new(Box::pin(()), |_| Box::leak(Box::new(Cell::new(""))));
    let s = String::from("Hello World");
    x.referential().set(&s);
    let r: &str = x.referential().get();
    println!("String exists: {r}");
    drop(s);
    println!("String used after free: {r}");
}
```

**Comment by prokopyl** [comment]
Hi, and thanks for your detailed report!

I think the issues you are describing only apply to an older version of Selfie though (I'm assuming `0.2`?).
On the latest version on main (https://github.com/prokopyl/selfie/commit/726013fc94835b6f24918ba822a49e5c3b2a3b25) I have already made fixes to the lifetimes in `with_referential[_mut]`, following the discussion on the [rust forum](https://users.rust-lang.org/t/soundness-review-for-selfie-my-personal-self-referential-struct-library/79010/2?u=prokopyl).

I think the changes in that commit fix the issues you've been describing, as the examples you provide do not pass the borrow checker anymore, and the `referential` method is gone (since indeed it is impossible to write as of now). Of course if you could double-check that it is actually the case, that would be very helpful. :slightly_smiling_face: 

Another issue here is also that I completely forgot to release `v0.3` with those fixes. As per [that same forum thread](https://users.rust-lang.org/t/soundness-review-for-selfie-my-personal-self-referential-struct-library/79010/14), it seems my current approach is most likely unsound anyway, so I ended up stopping to work on the project altogether.

I had the idea to leverage `async` function for self-referential purposes instead (see the [`async`](https://github.com/prokopyl/selfie/tree/async) branch), but I couldn't make it work, and I just found out [`nolife`](https://github.com/dureuill/nolife) beat me to it anyway! (On top of seemingly being actually sound *and* having a smart name too!)

I'll make a `v0.3` release with the aforementioned fixes so that my few users get to at least have *less* unsoundness, and then I'll follow up by properly archiving the project, and referring to other projects like [`ouroboros`](https://github.com/someguynamedjosh/ouroboros) or [`nolife`](https://github.com/dureuill/nolife), which actually seem to be sound.

**Comment by steffahn** [comment]
Ah, yes, I haven't looked at the latest version from the repo I suppose.

**Comment by prokopyl** [comment]
Yes, that's my bad, I should have published it on crates.io a while ago. I just uploaded `v0.0.3` with the fixes and yanked the previous versions, and I properly marked the library as unsound in the `README.md` file.

Thanks a lot for your help by the way, here and on the forums. Even if this experiment didn't pan out, your work is very much appreciated. :slightly_smiling_face:
